name: main
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.22.0'
          kubernetes version: 'v1.21.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - run: mkdir -p "$HOME/.local/bin"
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: echo "SKUPPER_URL=$(curl -sL https://api.github.com/repos/skupperproject/skupper/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux-amd64")) | .browser_download_url')" >> $GITHUB_ENV
      - run: curl -sL $SKUPPER_URL | tar -C "$HOME/.local/bin" -xzf -
      - run: skupper version
      - run: ./plano test
